name: Build
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: [ "8.1", "8.2" ]

    steps:
      - uses: actions/checkout@v3

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php_version }}
